### ISSUE TITLE
Random warnings for "Type application/netcdf is already registered as a variant of application/netcdf."

### ISSUE THREAD

**Issue by georf** [mime-types/ruby-mime-types#163]
I use rails 6.1.4.6 with mime-types 3.4.1 and have a random problem:

On my server a cronjob call several rake tasks every few minutes. Normal there is no output and I do not get an email with the cronjob output. But sometimes I get the message: `Type application/netcdf is already registered as a variant of application/netcdf.`

I tried it locally with this command: `while true ; do rails debug:failed_delayed_jobs ; date ; done` After 300 times it fails locally too. Here is the stack of the warning:

```
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types.rb:192:in `add_type'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types.rb:181:in `block in add'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types.rb:171:in `each'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types.rb:171:in `add'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:33:in `block in load_base_data'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:55:in `block (2 levels) in each_file_line'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:48:in `each'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:48:in `block in each_file_line'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:42:in `synchronize'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:42:in `each_file_line'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:25:in `load_base_data'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/loader.rb:72:in `load_columnar'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/loader.rb:84:in `load'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/loader.rb:93:in `load'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/registry.rb:69:in `load_default_mime_types'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/registry.rb:89:in `<class:Types>'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types/registry.rb:88:in `<main>'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/mime-types-3.4.1/lib/mime/types.rb:235:in `<main>'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/httparty-0.20.0/lib/httparty.rb:9:in `<main>'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'
/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler.rb:175:in `require'
/home/georf/workspace/vkg-bg-jobs/config/application.rb:24:in `<main>'
/home/georf/workspace/vkg-bg-jobs/Rakefile:6:in `require_relative'
/home/georf/workspace/vkg-bg-jobs/Rakefile:6:in `<main>'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/railties-6.1.4.6/lib/rails/command.rb:50:in `invoke'
/home/georf/.rvm/gems/ruby-3.0.3@vkg_bg_jobs/gems/railties-6.1.4.6/lib/rails/commands.rb:18:in `<main>'
```

I have absolutely no idea why this warning comes up at all, much less why it only appears every now and then. Can someone maybe give me a hint?

**Comment by georf** [comment]
Oh, why I didn't find this PR? Hmm. Okay, than I will downgrade to version [3.2021.1115](https://rubygems.org/gems/mime-types-data/versions/3.2021.1115) of mime-types-data.
